[package]
name = "a_star"
version = "0.1.0"
authors = ["christian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.4.*"
priority-queue = "0.6.*"
stopwatch = "0.0.*"